name: Project

env:
  COMPOSE_USER: root

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  code-analysis:
    name: PHP - Code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: go-task/setup-task@v1
      # https://github.com/ddev/github-action-setup-ddev
      - uses: ddev/github-action-setup-ddev@v1

      - name: Start DDEV
        run: task ddev:start

      - name: Code analysis
        run: task code-analysis:phpstan

      - name: Rector
        run: task rector -- --dry-run
